package db

import (
	"context"
	"fmt"
	"log"

	"github.com/0x03ff/golang/internal/store/repositories"
	"github.com/jackc/pgx/v5/pgxpool"
)

func db_init(dropFlag bool, pool *pgxpool.Pool) error {
	ctx := context.Background()

	var err error

	if dropFlag {
		// Drop the tables if they exist
		tables := []string{"users", "system_keys", "files", "folders"}
		for _, table := range tables {
			_, err = pool.Exec(ctx, "DROP TABLE IF EXISTS "+table)
			if err != nil {
				return err
			}

		}
		fmt.Println("Dropped tables")
	}

	_, err = pool.Exec(ctx, `
		CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
	`)
	if err != nil {
		return err
	}

	fmt.Println("Created extension")

	// Create the users table
	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS users (
			id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
			username VARCHAR(255) NOT NULL UNIQUE,
			password VARCHAR(255) NOT NULL,
			recover VARCHAR(255) NOT NULL,
			ecdh_public_key BYTEA NOT NULL,
			ecdh_encrypt_private_key BYTEA NOT NULL,
			created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return err
	}
	fmt.Println("Created users table")

	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS system_keys (
			id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
			public_key BYTEA NOT NULL,
			private_key BYTEA NOT NULL,
			ecdh_public_key  BYTEA NOT NULL,
			ecdh_private_key BYTEA NOT NULL
		);
	`)
	if err != nil {
		return err
	}
	fmt.Println("Created system_keys table")

	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS files (
			id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR(255) NOT NULL,
			user_id UUID NOT NULL,
			file_path VARCHAR(255) NOT NULL,
			extension VARCHAR(10) NOT NULL DEFAULT 'bin',
			created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
		);



`)
	if err != nil {
		return err
	}

	fmt.Println("Created files table")

	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS folders (
			id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR(255) NOT NULL,
			user_id UUID NOT NULL,
			file_path VARCHAR(255) NOT NULL,
			secret BYTEA,
			private_key BYTEA,
			encrypt VARCHAR(50) NOT NULL DEFAULT 'non-encrypted',
			extension VARCHAR(10) NOT NULL DEFAULT 'bin',
			created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
		);
	`)
	if err != nil {
		return err
	}

	fmt.Println("Created folders table")

	if dropFlag {
		// Create a new storage instance


	
		ctx := context.Background()

		



		publicKey, privateKey, err := repositories.GenerateECDSAKeyPair()
		if err != nil {
			log.Fatalf("Failed to generate ECDSA key pair: %v", err)
		}




		ecdh_publicKey, ecdh_privateKey, err := repositories.GenerateECDHKeyPair()
		if err != nil {
			log.Fatalf("Failed to generate ECDH key pair: %v", err)
		}




		// Insert the keys into the system_keys table
		_, err = pool.Exec(ctx, `
			INSERT INTO system_keys (public_key, private_key,ecdh_public_key,ecdh_private_key)
			VALUES ($1, $2,$3,$4)
		`, publicKey, privateKey,ecdh_publicKey,ecdh_privateKey)
		if err != nil {
			log.Fatalf("Failed to insert keys into system_keys table: %v", err)
		}

		fmt.Println("Inserted keys into system_keys table")
		

	}


	return nil
}
